const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { createServer } = require('../server.cjs');
test('accounts isolate data, persist sessions, recover passwords, revoke logouts and migrate legacy only with proof', async t => {
    const dataDir = fs.mkdtempSync(path.join(__dirname, '../artifacts/accounts-test-'));
    const messages = []; const mailer = { configured: true, send: async message => messages.push(message) };
    const registrations = new Map();
    let app = createServer({ dataDir, mailer });
    await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
    t.after(() => new Promise(resolve => app.server.close(resolve)));
    let base = 'http://127.0.0.1:' + app.server.address().port;
    const api = async (route, method = 'GET', data, token = '') => {
        if (route === 'auth/register' && !data.email) {
            const email = data.username.toLowerCase() + '@example.com';
            if (!registrations.has(email)) registrations.set(email, api('auth/email-code', 'POST', { email, purpose: 'register' }).then(result => ({ email, challengeId: result.challengeId, code: messages.find(m => m.to === email).code })));
            data = { ...data, ...await registrations.get(email) };
        }
        const res = await fetch(base + '/api/' + route, { method, headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, body: data ? JSON.stringify(data) : undefined });
        return { status: res.status, ...(await res.json()) };
    };
    const password = 'test-passphrase-123';
    const alice = await api('auth/register', 'POST', { username: 'Alice', password });
    const bob = await api('auth/register', 'POST', { username: 'Bob', password });
    assert.equal(alice.status, 200); assert.ok(alice.recoveryCode); assert.ok(alice.token.startsWith('bb_'));
    assert.equal((await api('auth/register', 'POST', { username: 'ALICE', password })).status, 400);
    assert.equal((await api('auth/login', 'POST', { username: 'alice', password: 'wrong-password' })).status, 401);
    const phone = await api('auth/login', 'POST', { username: 'alice', password });
    const created = await api('tasks', 'POST', { title: '电脑写下的事' }, alice.token);
    assert.equal(created.reminder, 30);
    assert.equal((await api('tasks', 'GET', null, phone.token)).tasks[0].title, '电脑写下的事');
    assert.equal((await api('tasks', 'GET', null, bob.token)).tasks.length, 0);
    assert.equal((await api('tasks/' + created.id, 'DELETE', { revision: 1 }, bob.token)).status, 404);
    await api('tasks', 'POST', { title: '旧空间事项' }, app.db.token);
    assert.equal((await api('auth/migrate', 'POST', { legacyToken: 'wrong' }, bob.token)).status, 400);
    assert.equal((await api('auth/migrate', 'POST', { legacyToken: app.db.token }, alice.token)).migrated, 1);
    assert.equal((await api('auth/migrate', 'POST', { legacyToken: app.db.token }, alice.token)).migrated, 0);
    assert.equal((await api('tasks', 'GET', null, app.db.token)).status, 401);
    assert.equal((await api('auth/migrate', 'POST', { legacyToken: app.db.token }, bob.token)).status, 400);
    assert.equal(app.db.tasks.length, 1, 'legacy source remains archived');
    const disk = fs.readFileSync(path.join(dataDir, 'space.json'), 'utf8');
    assert.ok(!disk.includes(password)); assert.ok(!disk.includes(alice.token)); assert.ok(!disk.includes(alice.recoveryCode));
    await new Promise(resolve => app.server.close(resolve)); app = createServer({ dataDir, mailer });
    await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve)); base = 'http://127.0.0.1:' + app.server.address().port;
    assert.equal((await api('tasks', 'GET', null, phone.token)).tasks.length, 2);
    await api('auth/logout', 'POST', {}, phone.token);
    assert.equal((await api('tasks', 'GET', null, phone.token)).status, 401);
    assert.equal((await api('tasks', 'GET', null, alice.token)).status, 200);
    const recovered = await api('auth/recover', 'POST', { username: 'alice', recoveryCode: alice.recoveryCode, password: 'new-passphrase-123' });
    assert.equal(recovered.status, 200); assert.notEqual(recovered.recoveryCode, alice.recoveryCode);
    assert.equal((await api('tasks', 'GET', null, alice.token)).status, 401);
    assert.equal((await api('tasks', 'GET', null, recovered.token)).tasks.length, 2);
    assert.equal((await api('auth/recover', 'POST', { username: 'alice', recoveryCode: alice.recoveryCode, password })).status, 401);
    const races = await Promise.all([api('auth/register', 'POST', { username:'race',password }), api('auth/register','POST',{username:'race',password})]);
    assert.deepEqual(races.map(x => x.status).sort(), [200, 400]);
});
