const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createServer } = require('../server.cjs');
const { createMailer } = require('../email.cjs');
test('verified registration, bound legacy email, isolated single-use codes, expiry, failure and reset revocation', async t => {
    let now = Date.now(); const messages = []; let broken = false;
    const mailer = { configured: true, send: async m => { if (broken) throw Error('smtp-password-must-not-leak'); messages.push(m); } };
    const dataDir = fs.mkdtempSync(path.join(__dirname, '../artifacts/email-test-'));
    let app = createServer({ dataDir, mailer, now: () => now });
    await new Promise(r => app.server.listen(0, '127.0.0.1', r));
    let base = 'http://127.0.0.1:' + app.server.address().port;
    t.after(() => new Promise(r => app.server.close(r)));
    let n = 0;
    const api = async (route, data, token = '') => {
        const response = await fetch(base + '/api/auth/' + route, { method: data === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token }, body: data === undefined ? undefined : JSON.stringify(data) });
        return { status: response.status, ...await response.json() };
    };
    const password = 'test-email-password-123';
    async function code(email, purpose = 'register', token = '', extra = {}) {
        const result = await api('email-code', {email, purpose, ...extra}, token);
        assert.equal(result.status, 200, JSON.stringify(result));
        return { email, challengeId: result.challengeId, code: messages.filter(m => m.to === email.toLowerCase()).at(-1)?.code };
    }
    assert.equal((await api('register', {username: 'missing', password})).status, 400);
    assert.equal((await api('email-code', {email:'bad\r\n@example.com',purpose:'register'})).status, 400);
    const proof = await code('Alice@Example.com');
    assert.equal(app.db.accounts.length, 0, 'sending a code does not create an account');
    assert.equal((await api('email-code', {email:proof.email,purpose:'register'})).status, 429);
    assert.equal((await api('register', {username:'alice',password,...proof,code:'bad'})).status, 400);
    const alice = await api('register', {username:'alice',password,...proof});
    assert.equal(alice.status, 200); assert.equal(alice.user.email,'alice@example.com'); assert.equal(alice.user.emailVerified,true);
    assert.equal((await api('register',{username:'reuse',password,...proof})).status,400);
    const bob = await api('register',{username:'bob',password,...await code('bob@example.com')}); assert.equal(bob.status,200);
    const phone = await api('login',{username:'alice',password});
    app.db.accounts.find(a => a.username === 'alice').subscriptions.push({sessionHash:'old'});
    now += 60001;
    const reset = await code('alice@example.com','reset');
    assert.equal((await api('email-reset',{...reset,email:'bob@example.com',password})).status,400);
    assert.equal((await api('register',{username:'crossuse',password,...reset})).status,400);
    const disk=fs.readFileSync(path.join(dataDir,'space.json'),'utf8');
    assert.ok(!disk.includes('"code":')); assert.ok(!disk.includes(alice.token)); assert.ok(!disk.includes(password));
    await new Promise(r => app.server.close(r)); app=createServer({dataDir,mailer,now:()=>now});
    await new Promise(r => app.server.listen(0,'127.0.0.1',r)); base='http://127.0.0.1:'+app.server.address().port;
    const results=await Promise.all([api('email-reset',{...reset,password:'new-email-password-123'}),api('email-reset',{...reset,password:'new-email-password-123'})]);
    assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);
    assert.equal((await api('me',undefined,alice.token)).status,401);assert.equal((await api('me',undefined,phone.token)).status,401);
    assert.equal((await api('me',undefined,bob.token)).status,200);
    assert.equal(app.db.accounts.find(a=>a.username==='alice').subscriptions.length,0);
    assert.equal((await api('recover',{username:'alice',recoveryCode:alice.recoveryCode,password})).status,401);
    assert.equal((await api('login',{username:'alice',password:'new-email-password-123'})).status,200);
    const unknownCount=messages.length; const unknown=await code('unknown@example.com','reset');
    assert.equal(messages.length,unknownCount,'unknown address gets no mail'); assert.ok(unknown.challengeId);
    assert.equal((await api('email-reset',{...unknown,code:'000000',password})).status,400);
    const legacy=app.db.accounts.find(a=>a.username==='bob'); delete legacy.email;delete legacy.emailVerifiedAt;
    assert.equal((await api('email-code',{email:'legacy@example.com',purpose:'bind',password})).status,401);
    assert.equal((await api('email-code',{email:'legacy@example.com',purpose:'bind',password:'wrong-password'},bob.token)).status,401);
    const bind=await code('legacy@example.com','bind',bob.token,{password});
    assert.equal((await api('email-bind',{...bind,password},results.find(x=>x.status===200).token)).status,400);
    const bound=await api('email-bind',{...bind,password},bob.token);assert.equal(bound.status,200);assert.equal(bound.user.emailVerified,true);
    const expiry=await code('expire@example.com'); now += 600001;
    assert.equal((await api('register',{username:'expired',password,...expiry})).status,400);
    const locked=await code('locked@example.com');
    for(let i=0;i<5;i++) assert.equal((await api('register',{username:'locked',password,...locked,code:'wrong'})).status,400);
    assert.equal((await api('register',{username:'locked',password,...locked})).status,400);
    broken=true;const failed=await api('email-code',{email:'failure@example.com',purpose:'register'});assert.equal(failed.status,503);assert.ok(!failed.error.includes('smtp-password'));
    assert.ok(!app.db.emailChallenges.some(c=>c.email==='failure@example.com'));
    assert.equal(createMailer({}).configured,false);
    await assert.rejects(createMailer({}).send({}),e=>e.status===503);
});
